*1;
proc sort data=sasuser.pilots out=work.pilots;
by state;
run;
data work.pilotjob (drop=salary);
set work.pilots(keep=state salary);
by state;
if first.state then totalPay=0;
totalpay+salary;
if last.state;
run;
proc print data= work.pilotjob noobs;
sum totalpay;
format totalpay dollar12.0;
run;

*2;
proc sort data= sasuser.pilots out=work.pilots;
by jobcode;
run;
data work.pilotjob (drop=salary);
set work.pilots(keep=jobcode salary);
by jobcode;
if first.jobcode then totalpay=0;
totalpay+salary;
if last.jobcode;
run;
proc print data=work.pilotjob noobs;
sum totalpay;
format totalpay dollar12.0;
run;
